nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        paths:
            /api/auth/login:
                post:
                    summary: "User login"
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        login:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: "Successful login"
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                            refreshToken:
                                                type: string
                        '401':
                            description: "Invalid credentials"
            /api/auth/refresh:
                post:
                    summary: "Refresh JWT token"
                    responses:
                        '200':
                            description: "Token refreshed"
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '403':
                            description: "Token refresh denied"
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
