### post
POST http://localhost:8876/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "login":"superUser",
  "email":"test@test.com",
  "password":"se$cDr1et"
}

### get all
GET http://localhost:8876/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

### get
GET http://localhost:8876/api/user/4
Content-Type: application/json
Authorization: Bearer {{token}}

### put
PUT http://localhost:8876/api/user/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "login":"new_uper-user",
  "email":"new_test@test.com",
  "role": "ROLE_ADMIN"
}

### delete
DELETE http://localhost:8876/api/user/3
Content-Type: application/json
Authorization: Bearer {{token}}