parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    App\Users\Domain\Factory\UserFactory:
        arguments:
            $passwordHasher: '@App\Users\Domain\Service\UserPasswordHasherInterface'

    _instanceof:
        App\Shared\Application\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
        App\Shared\Application\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

    App\Users\UI\Controller\:
        resource: '../src/Users/UI/Controller/'
        tags: [ 'controller.service_arguments' ]